In [97]:
import cv2, tqdm
import pandas as pd

In [99]:
df = pd.read_csv('wiki_imdb_lfw.csv')

In [101]:
H, W, C = [], [], []
for i, path in tqdm.tqdm(enumerate(df.path)):
    try:
        img = cv2.imread(path)
        if img is not None:
            height, width, channel = img.shape
        else:
            height, width, channel = None, None, None
        H.append(height)
        W.append(width)
        C.append(channel)
    except FileNotFoundError as e:
        print(f"{i} Error: {e}")

536284it [1:09:05, 129.38it/s]

In [104]:
df['height'] = H
df['width'] = W
df['channels'] = C

# Discard not appropriate images from dataset

Policy: 
1. Image is not found;
2. Image height or width is less than 32 pixels.

In [174]:
include = []

for i in tqdm.trange(0, len(df)):
    height = df.height[i]
    width = df.width[i]
    if height is None:
        include.append(False)
        continue
    elif height < 32 or width < 32:
        include.append(False)
        continue
    include.append(True)

100%|███████████████████████████████████████████████████████████████████████| 536284/536284 [00:08<00:00, 64585.87it/s]

In [176]:
df['include'] = include
# df.to_csv('wiki_imdb_lfw.csv', index=False)

In [182]:
df[df.include == False].dataset.value_counts()

dataset
wiki    8072
imdb       2
Name: count, dtype: int64

In [227]:
df[df.include == False][['dataset', 'height']].groupby('dataset', as_index=False).mean()

  dataset    height
0    imdb  26.50000
1    wiki   1.00669

In [229]:
df[df.include == False][['height']].describe()

            height
count  8074.000000
mean      1.013005
std       0.590569
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max      31.000000